### PR TITLE
Initial Gallery View

### PR DESCRIPTION
**Pull request by srijanpal1405**
Initial Gallery added!!
cc: @forkbabu @Fork-chan

### CODE REVIEW

**Comment by 0xf0f00f** [comment]
@forkbabu  where heroku?

**Comment by ucalyptus2** [comment]
oh lmao wait 45 mins por dekhchi

**Comment by ucalyptus2** [comment]
@srijanpal1405 Gemfile.lock add kor

**Comment by ucalyptus2** [comment]
@Fork-chan @srijanpal1405 DM me on discord your email-ids that are used for your respective github accounts.

**Comment by ucalyptus2** [comment]
@srijanpal1405 u might want to resolve the conflict in `Gemfile.lock`

**Comment by ucalyptus2** [comment]
@srijanpal1405 resolved this?

**Comment by Dsantra92** [comment]
I am closing this pr because of three reasons:
- Branch is weired diverged from upstream/main.
- We are going for CDN and we uploading photos in git is not required anymore.
- Lot of boilerplate code.

**Pull request closed without merging**
